# Generated by Django 6.0.5 on 2026-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_events', '0002_initial'),
        ('rides', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['id_ride', 'created_at'], name='idx_rideevent_ride_createdat'),
        ),
    ]
