# Generated by Django 6.0.5 on 2026-05-08 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='idx_ride_status'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='idx_ride_pickup_time'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['id_rider', 'status'], name='idx_ride_rider_status'),
        ),
    ]
